// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqWJ29aLiNglwrRHnm5zR4M1wZYOU2bSc',
    appId: '1:836934023854:web:b3a4b1b9728f0f9d238b3f',
    messagingSenderId: '836934023854',
    projectId: 'beaminclone',
    authDomain: 'beaminclone.firebaseapp.com',
    storageBucket: 'beaminclone.firebasestorage.app',
    measurementId: 'G-Y8PN8ZPC9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5vNUfCz8NrF_Gzm9UougWUBFlnYl91s',
    appId: '1:836934023854:android:d9fd422e01507f05238b3f',
    messagingSenderId: '836934023854',
    projectId: 'beaminclone',
    storageBucket: 'beaminclone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4RkWp4cp3aTjRLbB5e-ln7Kk4uM807U',
    appId: '1:836934023854:ios:8a98371472e8b51d238b3f',
    messagingSenderId: '836934023854',
    projectId: 'beaminclone',
    storageBucket: 'beaminclone.firebasestorage.app',
    androidClientId: '836934023854-shqlgsbcf99qskl0uvlkjdrce69oo4q6.apps.googleusercontent.com',
    iosClientId: '836934023854-fuf04cdfinm0c44sarcmfs7d6qi72h5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.beaminClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4RkWp4cp3aTjRLbB5e-ln7Kk4uM807U',
    appId: '1:836934023854:ios:8a98371472e8b51d238b3f',
    messagingSenderId: '836934023854',
    projectId: 'beaminclone',
    storageBucket: 'beaminclone.firebasestorage.app',
    androidClientId: '836934023854-shqlgsbcf99qskl0uvlkjdrce69oo4q6.apps.googleusercontent.com',
    iosClientId: '836934023854-fuf04cdfinm0c44sarcmfs7d6qi72h5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.beaminClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqWJ29aLiNglwrRHnm5zR4M1wZYOU2bSc',
    appId: '1:836934023854:web:ebe62aa7d1f2571e238b3f',
    messagingSenderId: '836934023854',
    projectId: 'beaminclone',
    authDomain: 'beaminclone.firebaseapp.com',
    storageBucket: 'beaminclone.firebasestorage.app',
    measurementId: 'G-CZ95N1SVHM',
  );
}
